### ISSUE TITLE
Properly handle unicode strings outside of the BMP

### ISSUE THREAD

**Issue by rearadmiral** [huang47/nodejs-html-truncate#18]
Because of javascript's [poor implementation of unicode](https://mathiasbynens.be/notes/javascript-unicode), this library will split certain unicode characters and cause a broken result.

Example:

``` javascript
var trunc = require("html-truncate");
trunc("☃💩☃", 2) => "☃�..."
```

Emoji are the most popular characters where this will happen and are pretty common for user content these days.

**Comment by arendjr** [comment]
If this is still a problem for you, you might want to give [text-clipper](https://github.com/arendjr/text-clipper) a try!

**Comment by bky** [comment]
@rearadmiral Did you find a solution to this problem?

**Comment by rearadmiral** [comment]
No I just used a different library

**Comment by bky** [comment]
Can I ask which library?

**Comment by rearadmiral** [comment]
Ehhh sorry it's been too long. I tried a bunch out and none of them were that great. In the end, for the actual solution I moved the truncation logic to server-side in ruby and used an also-broken gem to do it.
